spring:
  datasource:
    url: jdbc:mysql://localhost/community?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    #&serverTimezone=GMT%2B8
    username: root
    password: 13177281217liLEI?
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    #开发阶段禁用缓存
    cache: false
mybatis:
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true